In [1]:
!pip install fastavro

Requirement already satisfied: fastavro in c:\users\kebe\anaconda3\lib\site-packages (1.9.3)

Question: Définir un schema Avro

In [2]:
from fastavro import writer, reader, parse_schema

In [3]:
schema={
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields':[
        {'name':'station','type':'string'},
        {'name':'time','type':'long'},
        {'name':'temp','type':'int'}
    ],
}

Ecrire des records dans les fichiers Avro

In [4]:
parsed_schema=parse_schema(schema)
records=[
    {u'station': u'011990-99999',u'temp':1,u'time':1433269388},
    {u'station':u'011990-99999',u'temp':23,u'time':1433269389},
    {u'station':u'011990-99999',u'temp':-11,u'time':1433269390}
]
with open("weather.avro","wb") as out:
    writer(out, parsed_schema,records)

Lire le fichier Avro

In [5]:
with open('weather.avro','rb') as file:
    for record in reader(file):
        print(record)

{'station': '011990-99999', 'time': 1433269388, 'temp': 1}
{'station': '011990-99999', 'time': 1433269389, 'temp': 23}
{'station': '011990-99999', 'time': 1433269390, 'temp': -11}

In [10]:
import pandavro as pdx
pdx.read_avro('weather.avro').head()

        station        time  temp
0  011990-99999  1433269388     1
1  011990-99999  1433269389    23
2  011990-99999  1433269390   -11

In [7]:
!pip install pandavro

Requirement already satisfied: pandavro in c:\users\kebe\anaconda3\lib\site-packages (1.8.0)
Requirement already satisfied: fastavro<2.0.0,>=1.5.1 in c:\users\kebe\anaconda3\lib\site-packages (from pandavro) (1.9.3)
Requirement already satisfied: pandas>=1.1 in c:\users\kebe\anaconda3\lib\site-packages (from pandavro) (2.0.3)
Requirement already satisfied: numpy>=1.15.4 in c:\users\kebe\anaconda3\lib\site-packages (from pandavro) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kebe\anaconda3\lib\site-packages (from pandas>=1.1->pandavro) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\kebe\anaconda3\lib\site-packages (from pandas>=1.1->pandavro) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\kebe\anaconda3\lib\site-packages (from pandas>=1.1->pandavro) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\kebe\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.1->pandavro) (1.16.0)

In [11]:
import numpy as np
import pandas as pd
import pandavro as pdx
filename="df.avro"

df = pd.DataFrame({"Boolean": [True, False, True, False],
                    "Float64": np.random.randn(4),
                    "Int64": np.random.randint(0, 10, 4),
                    "String": ['foo', 'bar', 'foo', 'bar'],
                    "DateTime64": [pd.Timestamp('20190101'), pd.Timestamp('20190102'),
                                  pd.Timestamp('20190103'), pd.Timestamp('20190104')]})

pdx.to_avro(filename,df)

In [19]:
data=pdx.read_avro(filename)
data.head()

   Boolean   Float64  Int64 String                DateTime64
0     True  0.022629      1    foo 2019-01-01 00:00:00+00:00
1    False  0.022990      7    bar 2019-01-02 00:00:00+00:00
2     True  1.147094      2    foo 2019-01-03 00:00:00+00:00
3    False -0.793433      8    bar 2019-01-04 00:00:00+00:00

help(pdx.read_avro)
read_avro(file_path_or_buffer, schema=None, na_dtypes=False, columns: Optional[Iterable[str]] = None, **kwargs)

# Parquet

Ecrire un fichier Parquet

In [ ]:
import pyarrow as pa
import pyarrow.parquet as pq
table=pa.Table.from_pandas(df)
pq.write_table(table,"df.parquet")

In [ ]:
pq.read_table("df.parquet").to_pandas()

In [ ]:
pq.read_pandas('df.parquet',columns=['String','Int64','Boolean']).to_pandas()

Comparaison Avro et Parquet

In [ ]:
import pyarrow.parquet as pq
import pyarrow as pa
import pandavro as pdx

filename_avro="df_test.avro"
filename_parquet="df_test.parquet"
df=pd.DataFrame({"a":range(1000)})
pdx.to_avro(filename_avro,df)
pq.write_table(pa.Table.from_pandas(df),filename_parquet)

ls -lh

Compression avec Parquet

In [ ]:
!pip install libsnappy-dev
!pip install python-snappy

In [ ]:
pq.write_table(pa.Table.from_pandas(df),'df_snappy.parquet',compression='snappy')
pq.write_table(pa.Table.from_pandas(df),'df_gzip.parquet',compression="gzip")

!ls -lh